variable "access_key" {}
variable "secret_key" {}
variable "token" {}
variable "vpc_cidr_block" {}
variable "subnet_cidr_block" {}
variable "avail_zone" {}
variable "env_prefix" {}
variable "my_ip" {}
variable "instance_type" {}
variable "public_key_location" {}
variable "key_name" {}
variable "bucket_name" {}
variable "dynamoDB_name" {}